version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
    working_directory: ~/docker-lesson-repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
            python 3 -m venv docker-lesson-repo
            . docker-lesson-repo/bin/activate
            make install
            
      - save_cache:
          paths:
            - ./docker-lesson-repo
          key: v1-dependencies-{{ checksum "requirements.txt" }}
            
      - run:
          name: run lint
          command: |
            . docker-lesson-repo/bin/activate
            make lint
          
      